# Development environment
FROM node:16-alpine

# Set app directory
WORKDIR /app

# Copy necessary files
COPY package.json ./
COPY package-lock.json ./
COPY .eslintrc.js ./
COPY tsconfig.json ./

# Ensure webpack.config.ts exists before copying
COPY webpack.config.ts ./ # Remove this line if the file is not needed

# Install dependencies
RUN npm install

# Expose the port
EXPOSE 3000

# Start the application
CMD ["npm", "start"]
